# Generated by Django 5.0.4 on 2024-04-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Men', models.CharField(max_length=300, unique=True)),
                ('Women', models.TextField()),
            ],
        ),
    ]
